<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/helloworld.proto

namespace GPBMetadata\Proto;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3020a1670726f746f2f68656c6c6f776f726c642e70726f746f120a68" .
            "656c6c6f776f726c64221c0a0c48656c6c6f52657175657374120c0a046e" .
            "616d65180120012809221d0a0a48656c6c6f5265706c79120f0a076d6573" .
            "73616765180120012809328e010a0747726565746572123e0a0853617948" .
            "656c6c6f12182e68656c6c6f776f726c642e48656c6c6f52657175657374" .
            "1a162e68656c6c6f776f726c642e48656c6c6f5265706c79220012430a0d" .
            "53617948656c6c6f416761696e12182e68656c6c6f776f726c642e48656c" .
            "6c6f526571756573741a162e68656c6c6f776f726c642e48656c6c6f5265" .
            "706c79220042670a1b696f2e677270632e6578616d706c65732e68656c6c" .
            "6f776f726c64420f48656c6c6f576f726c6450726f746f50015a35676f6f" .
            "676c652e676f6c616e672e6f72672f677270632f6578616d706c65732f68" .
            "656c6c6f776f726c642f68656c6c6f776f726c64620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

